/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Class.Configuracion.Empresa;
import Class.productos.Producto;
import Class.productos.funciones_productos;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Class.productos.Producto;
import Class.venta.Detalleventa;
import Class.venta.funciones_venta;
import Class.venta.ventas;
import java.util.List;

/**
 *
 * @author admi
 */
public class NuevaVenta_interfaz extends javax.swing.JFrame {
    DefaultTableModel modelo;
    double totalpagar =0.0;
    int item;
    double subtotal=0.0;
    double igv=0.0;
    private String cantidad;
    private int id_producto;
    ventas v =new ventas();
    Producto pro = new Producto(id_producto);
    funciones_venta fv =new funciones_venta();
    funciones_productos prodao =new funciones_productos();
    Detalleventa dv =new Detalleventa();
    public NuevaVenta_interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        inhabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        txtcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtdnicliente = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtidproducto = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtpago = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtigv = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir_hover.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 80, 50));
        getContentPane().add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STOCK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DNI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 20));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 140, -1));
        getContentPane().add(txtdnicliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 130, -1));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAGO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 60, 20));

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id producto", "Producto", "precio", "cantidad", "precio total"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 710, 100));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CANTIDAD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, 20));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 140, -1));
        getContentPane().add(txtidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID PRODUCTO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 20));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRODUCTO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 90, 20));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRECIO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 70, 20));
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 140, -1));

        txtpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 140, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 70, 20));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IGV");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 20));

        jButton3.setText("Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        txtigv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtigvActionPerformed(evt);
            }
        });
        getContentPane().add(txtigv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 140, -1));

        jButton2.setText("GENERAR VENTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 210, 30));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SUB TOTAL");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 20));
        getContentPane().add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 70, -1));

        txtimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portallogin7.jpg"))); // NOI18N
        txtimg.setText("jLabel1");
        getContentPane().add(txtimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Sistema sis =new Sistema();
        sis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       
                
                 ActualizarStock();
        RegistrarVenta();
        RegistrarDetalle();
        pdf();
        LimpiarVenta();
        for(int i=0;i<tablaventas.getRowCount();i++)
 {
     modelo.removeRow(i);
     i=i-1;
 }       
          
    
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtigvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtigvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtigvActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Carrito_interfaz dialog = new Carrito_interfaz(new javax.swing.JFrame(), true);
      dialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtcantidad.getText())) {
                String cod = txtidproducto.getText();
                String descripcion = txtnombre.getText();
                int cant = Integer.parseInt(txtcantidad.getText());
                double precio = Double.parseDouble(txtprecio.getText());
                
                double total = cant * precio;
                int stock = Integer.parseInt(txtstock.getText());
                if (stock >= cant) {
                    item = item + 1;
                    modelo= (DefaultTableModel) tablaventas.getModel();
                    for (int i = 0; i < tablaventas.getRowCount(); i++) {
                        if (tablaventas.getValueAt(i, 2).equals(txtnombre.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            LimpiarVenta();
                            return;
                        }
                    }
                    
                    ArrayList lista = new ArrayList();
                    lista.add(item);
                    lista.add(cod);
                    lista.add(descripcion);
                    lista.add(precio);
                    lista.add(cant);
                    lista.add(total);
                    
                    Object[] O = new Object[6];
                    O[0] = lista.get(1);
                    O[1] = lista.get(2);
                    O[2] = lista.get(3);
                    O[3] = lista.get(4);
                    O[4] = lista.get(5);
                   
                    modelo.addRow(O);
                    tablaventas.setModel(modelo);
                    TotalPagar();
                    limpiarproducto();
                    txtnombre.requestFocus();
                    
                  
                } else {
                    JOptionPane.showMessageDialog(null, "No disponemos de esa cantidad en el stock");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Cantidad");
            }
        }         
    }//GEN-LAST:event_txtcantidadKeyPressed

     private void TotalPagar() {
        totalpagar = 0.000;
        int numFila = tablaventas.getRowCount();
        double igvs=0;
        for (int i = 0; i < numFila; i++) {
            double cal = Double.parseDouble(String.valueOf(tablaventas.getModel().getValueAt(i, 4)));
            totalpagar = totalpagar + cal;
            igv=totalpagar*0.19;
            igvs=igv;
            subtotal= totalpagar-igvs;
           
        }
        txttotal.setText(String.valueOf(totalpagar));
        txtsubtotal.setText(String.valueOf(subtotal));
        txtigv.setText(String.valueOf(igv));
        
    }
       private void ActualizarStock() {
            
             for (int i = 0; i < tablaventas.getRowCount(); i++) {
            int cod = Integer.parseInt(tablaventas.getValueAt(i, 0).toString());
            int cant = Integer.parseInt(tablaventas.getValueAt(i, 3).toString());
              pro = prodao.BuscarPro(cod);
            int StockActual = Integer.parseInt(pro.getStock()) - cant;
            prodao.ActualizarStock(StockActual, cod);
            
             
            
             }
    }
      private void RegistrarVenta()
{
    String dni_cliente=txtdnicliente.getText();
    String nombre_cliente=txtcliente.getText();
    int factura_detalle=Integer.parseInt(txtdnicliente.getText());
    double monto = totalpagar;
    v.setDni_cliente(dni_cliente);
    v.setNombre_cliente(nombre_cliente);
    v.setMonto_total(monto);
    v.setId_facturadetalle(factura_detalle);
    fv.RegistrarVenta(v);
}
private void RegistrarDetalle()
{
    for(int i=0;i<tablaventas.getRowCount();i++)
    {
        
        int cod = Integer.parseInt(txtdnicliente.getText());
        String nombre =tablaventas.getValueAt(i,1).toString();
        double precio =Double.parseDouble(tablaventas.getValueAt(i,2).toString());
        int cant=Integer.parseInt(tablaventas.getValueAt(i,3).toString());
        int id =1;
        
        dv.setId_facturadetalle(cod);
        dv.setProducto(nombre);
        dv.setPrecio(precio);
        dv.setCantidad(cant);
  
        fv.RegistrarDetalle(dv);
        
       
    }
}
     private void LimpiarVenta() {
        txtcliente.setText("");
        txtdnicliente.setText("");
        txtidproducto.setText("");
        txtnombre.setText("");
        txtcantidad.setText("");
        txtstock.setText("");
        txtprecio.setText("");
        txtsubtotal.setText("");
        txtigv.setText("");
        txttotal.setText("");
    }
     private void limpiarproducto()
     {
         txtidproducto.setText("");
        txtnombre.setText("");
        txtcantidad.setText("");
        txtstock.setText("");
        txtprecio.setText("");
       
     }
      void inhabilitar(){
        txtidproducto.setEnabled(false);
        txtnombre.setEnabled(false);
        txtstock.setEnabled(false);
        txtprecio.setEnabled(false);
       
        txtidproducto.setText("");
        txtnombre.setText("");
        txtstock.setText("");
        txtprecio.setText("");

    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVenta_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaventas;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtdnicliente;
    public static javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtigv;
    private javax.swing.JLabel txtimg;
    public static javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpago;
    public static javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtstock;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
private void pdf() {
        try {
            int id = 1;
            double vuelto=Double.parseDouble(txtpago.getText())-Double.parseDouble(txttotal.getText());
            System.out.println(vuelto);
            FileOutputStream archivo;
            File file = new File("src/pdf/venta" + id + ".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/img/productos.png");

            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Factura:" + id + "\n" + "Fecha: " +date.toString() + "\n\n");

            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            Encabezado.addCell(img);
            
            
            
            List <String> data = new ArrayList();
            data=Empresa.Call_Datos();

            Encabezado.addCell("");
            Encabezado.addCell("RUC: " +data.get(0)+ "\nNombre: " + data.get(3) + "\nTelefono: " + data.get(2) + "\nDireccion: " + data.get(4)+ "\nGerente: " + data.get(5));
            Encabezado.addCell(fecha);
            doc.add(Encabezado);

            Paragraph cli = new Paragraph();
            cli.add(Chunk.NEWLINE);
            cli.add("Datos de los clientes" + "\n\n");
            doc.add(cli);
            PdfPTable tablacli = new PdfPTable(2);
            tablacli.setWidthPercentage(100);
            tablacli.getDefaultCell().setBorder(0);
            float[] Columnacli = new float[]{40f,40f};
            tablacli.setWidths(Columnacli);
            tablacli.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cl1 = new PdfPCell(new com.itextpdf.text.Phrase("Dni", negrita));
            PdfPCell cl2 = new PdfPCell(new com.itextpdf.text.Phrase("Nombre", negrita));
         
            cl1.setBorder(0);
            cl2.setBorder(0);
          
            tablacli.addCell(cl1);
            tablacli.addCell(cl2);
    
            tablacli.addCell(txtdnicliente.getText());
            tablacli.addCell(txtcliente.getText());
            

            doc.add(tablacli);
    

            //productos
            PdfPTable tablapro = new PdfPTable(5);
            tablapro.setWidthPercentage(100);
            tablapro.getDefaultCell().setBorder(0);
            float[] Columnapro = new float[]{20f, 20f, 20f, 20f,20f};
            tablapro.setWidths(Columnapro);
            tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell pro1 = new PdfPCell(new com.itextpdf.text.Phrase("id producto", negrita));
            PdfPCell pro2 = new PdfPCell(new com.itextpdf.text.Phrase("Nombre", negrita));
            PdfPCell pro3 = new PdfPCell(new com.itextpdf.text.Phrase("Precio", negrita));
            PdfPCell pro4 = new PdfPCell(new com.itextpdf.text.Phrase("Cantidad", negrita));
            PdfPCell pro5 = new PdfPCell(new com.itextpdf.text.Phrase("Precio Total", negrita));
            pro1.setBorder(0);
            pro2.setBorder(0);
            pro3.setBorder(0);
            pro4.setBorder(0);
            pro5.setBorder(0);
            pro1.setBackgroundColor(BaseColor.WHITE);
            pro2.setBackgroundColor(BaseColor.WHITE);
            pro3.setBackgroundColor(BaseColor.WHITE);
            pro4.setBackgroundColor(BaseColor.WHITE);
            pro5.setBackgroundColor(BaseColor.WHITE);
            tablapro.addCell(pro1);
            tablapro.addCell(pro2);
            tablapro.addCell(pro3);
            tablapro.addCell(pro4);
            tablapro.addCell(pro5);
            
          
            for (int i = 0; i < tablaventas.getRowCount(); i++) {
            
                String id_producto=tablaventas.getValueAt(i, 0).toString();
                String producto = tablaventas.getValueAt(i, 1).toString();
                String precio = tablaventas.getValueAt(i, 2).toString();
                String cant = tablaventas.getValueAt(i, 3).toString();
                String total = tablaventas.getValueAt(i, 4).toString();
                tablapro.addCell(id_producto);
                tablapro.addCell(producto);
                tablapro.addCell(precio);
                tablapro.addCell(cant);
                tablapro.addCell(total);
            }
            
           doc.add(tablapro);

            Paragraph info = new Paragraph();
          
            Paragraph pago = new Paragraph();
             
            Paragraph total = new Paragraph();
            info.add(Chunk.NEWLINE);
            
            info.add("Pago :S/."+txtpago.getText()+".0");
            info.setAlignment(Element.ALIGN_RIGHT);
            doc.add(info);
            total.add(Chunk.NEWLINE);
            total.add("Total a pagar: S/."+txttotal.getText() );
            total.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(total);
            
            pago.add(Chunk.NEWLINE);
            pago.add("Vuelto: S/."+String.valueOf(vuelto) );
            pago.setAlignment(Element.ALIGN_RIGHT);
            doc.add(pago);
         

            Paragraph mensaje = new Paragraph();
            mensaje.add(Chunk.NEWLINE);
            mensaje.add("GRACIAS POR SU COMPRA COMPAÑERO");
            mensaje.setAlignment(Element.ALIGN_CENTER);
            doc.add(mensaje);
            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);
        } catch (DocumentException | IOException e) {
            System.out.println(e.toString());
        }
    }


}
